import { useMemo,useState } from 'react'
import { endings,events,shopItems } from './game/content'
import { applyEffects,eventById,getNarrativeEnding,initialState,meets,scoreRun } from './game/engine'
import { loadSave,saveGame,type SaveData } from './game/storage'
import type { Choice,GameState } from './game/types'
import './styles.css'

type Screen='home'|'run'|'result'|'shop'
type Snapshot={state:GameState;eventId:string;decisions:number}
type Result={score:number;coins:number;ending:string;state:GameState;decisions:number;canContinue:boolean}

function App(){
 const [screen,setScreen]=useState<Screen>('home');const [state,setState]=useState<GameState>(initialState);const [eventId,setEventId]=useState('morning');const [decisions,setDecisions]=useState(0);const [save,setSave]=useState<SaveData>(()=>loadSave());const [result,setResult]=useState<Result|null>(null);const [snapshot,setSnapshot]=useState<Snapshot|null>(null)
 const event=useMemo(()=>eventById(eventId),[eventId])
 const updateSave=(next:SaveData)=>{saveGame(next);setSave(next)}
 const startRun=()=>{let s={...initialState};const inv={...save.inventory};if((inv.coffee||0)>0){s.stress=Math.max(0,s.stress-10);inv.coffee--}if((inv.snacks||0)>0){s.coworkerTrust=Math.min(100,s.coworkerTrust+5);inv.snacks--}updateSave({...save,inventory:inv});setState(s);setEventId('morning');setDecisions(0);setSnapshot(null);setResult(null);setScreen('run')}
 const finish=(finalState:GameState,finalDecisions:number)=>{const score=scoreRun(finalState,finalDecisions);const ending=getNarrativeEnding(finalState,score);const bad=ending.id==='hr'||ending.id==='collapse';const canContinue=bad&&(save.inventory.continue||0)>0;if(canContinue){setResult({score,coins:Math.max(15,Math.round(score/5)),ending:ending.id,state:finalState,decisions:finalDecisions,canContinue:true});setScreen('result');return}const coins=Math.max(15,Math.round(score/5));const next={...save,coins:save.coins+coins,bestScore:Math.max(save.bestScore,score),history:[...save.history,{score,coins,ending:ending.id,decisions:finalDecisions,date:new Date().toISOString()}].slice(-20)};updateSave(next);setResult({score,coins,ending:ending.id,state:finalState,decisions:finalDecisions,canContinue:false});setScreen('result')}
 const choose=(choice:Choice)=>{const next=applyEffects(state,choice.effects);const nextDecisions=decisions+1;setSnapshot({state,eventId,decisions});setState(next);setDecisions(nextDecisions);if(choice.nextEvent==='ending')finish(next,nextDecisions);else setEventId(choice.nextEvent||'end')}
 const reroll=()=>{if(!snapshot||(save.inventory.reroll||0)<=0)return;updateSave({...save,inventory:{...save.inventory,reroll:save.inventory.reroll-1}});setState(snapshot.state);setEventId(snapshot.eventId);setDecisions(snapshot.decisions);setSnapshot(null)}
 const continueRun=()=>{if(!result||!result.canContinue)return;updateSave({...save,inventory:{...save.inventory,continue:save.inventory.continue-1}});setState(result.state);setDecisions(result.decisions);setEventId('recovery');setResult(null);setScreen('run')}
 const buy=(id:string)=>{const item=shopItems.find(x=>x.id===id);if(!item||save.coins<item.priceCoins)return;updateSave({...save,coins:save.coins-item.priceCoins,inventory:{...save.inventory,[id]:(save.inventory[id]||0)+1}})}
 const ending=endings.find(e=>e.id===result?.ending)
 return <main><header><button className="logo" onClick={()=>setScreen('home')}>CONSEQUENCES</button><div className="coins">🪙 {save.coins}</div></header>
 {screen==='home'&&<section className="hero"><span className="eyebrow">LA OFICINA</span><h1>Un día normal.<br/><em>Probablemente.</em></h1><p>Cada decisión cambia algo. Algunas cosas tardan un poco en romperse.</p><button className="primary" onClick={startRun}>▶ Nueva run</button><button className="secondary" onClick={()=>setScreen('shop')}>🛒 Shop</button>{save.bestScore>0&&<div className="best">Mejor score <strong>{save.bestScore}</strong></div>}</section>}
 {screen==='run'&&event&&<section className="game"><div className="stats">{[['💵','money'],['★','reputation'],['👔','bossTrust'],['🤝','coworkerTrust'],['⚡','stress'],['🔎','information']].map(([icon,key])=><div key={key}><span>{icon}</span><b>{state[key as keyof GameState]}</b><small>{key}</small></div>)}</div><div className="event"><span className="counter">DECISIÓN {decisions+1}</span><h2>{event.text}</h2><div className="choices">{event.choices.map(c=><button key={c.id} disabled={!meets(state,c.conditions)} onClick={()=>choose(c)}><span>{c.id.toUpperCase()}</span>{c.text}{!meets(state,c.conditions)&&<small>🔒 Requiere más información</small>}</button>)}</div>{snapshot&&<button className="utility" disabled={(save.inventory.reroll||0)<=0} onClick={reroll}>↶ Segunda opinión {save.inventory.reroll>0?`(${save.inventory.reroll})`:'(sin stock)'}</button>}</div></section>}
 {screen==='result'&&result&&ending&&<section className="result"><span className="eyebrow">{result.canContinue?'PUNTO DE QUIEBRE':'RUN TERMINADA'}</span><h1>{ending.title}</h1><p className="endingText">{ending.text}</p><div className="score"><small>SCORE</small><strong>{result.score}</strong></div>{result.canContinue?<><p>Tenés un <b>Modo “cinco minutos más”</b>. Podés gastar 1 para seguir la run.</p><button className="primary" onClick={continueRun}>⏱ Continuar la run</button></>:<><div className="reward">+{result.coins} 🪙 Coins</div><p>6 variables · {result.decisions} decisiones tomadas · {events.length} eventos en el escenario</p><button className="primary" onClick={startRun}>↻ Jugar otra vez</button></>}<button className="secondary" onClick={()=>setScreen('shop')}>🛒 Shop</button><div className="admock"><b>🎬 ¿Querés duplicar tus Coins?</b><span>Mock preparado para futura integración de anuncios.</span><button onClick={()=>{if(!result.canContinue){const next={...save,coins:save.coins+result.coins};updateSave(next)}}}>×2 recompensa (demo)</button></div></section>}
 {screen==='shop'&&<section className="shop"><span className="eyebrow">TIENDA</span><h1>Prepará tu próxima<br/><em>mala decisión.</em></h1><div className="items">{shopItems.map(item=><article key={item.id}><div><span className="pill">{item.type}</span><h3>{item.name}</h3><p>{item.description}</p></div><button disabled={save.coins<item.priceCoins} onClick={()=>buy(item.id)}>{item.priceCoins} 🪙</button>{save.inventory[item.id]>0&&<small>En inventario: {save.inventory[item.id]}</small>}</article>)}</div><button className="secondary" onClick={()=>setScreen('home')}>← Volver</button></section>}
 </main>
}
export default App
