import { useMemo, useState } from 'react'
import { events, shopItems } from './game/content'
import { applyEffects, eventById, getEnding, initialState, meets, scoreRun } from './game/engine'
import { defaultSave, loadSave, saveGame, type SaveData } from './game/storage'
import type { GameState } from './game/types'
import './styles.css'

type Screen='home'|'run'|'result'|'shop'
function App(){
 const [screen,setScreen]=useState<Screen>('home'); const [state,setState]=useState<GameState>(initialState); const [eventId,setEventId]=useState('morning'); const [decisions,setDecisions]=useState(0); const [save,setSave]=useState<SaveData>(()=>loadSave()); const [result,setResult]=useState<{score:number;coins:number;ending:string;state:GameState;decisions:number}|null>(null)
 const event=useMemo(()=>eventById(eventId),[eventId])
 const startRun=()=>{let s={...initialState}; const inv={...save.inventory}; if((inv.coffee||0)>0){s.stress=Math.max(0,s.stress-10);inv.coffee--;setSave(x=>({...x,inventory:inv}))} if((inv.snacks||0)>0){s.coworkerTrust=Math.min(100,s.coworkerTrust+5);inv.snacks--;setSave(x=>({...x,inventory:inv}))} setState(s);setEventId('morning');setDecisions(0);setResult(null);setScreen('run')}
 const finish=()=>{const score=scoreRun(state,decisions);const coins=Math.max(15,Math.round(score/5));const ending=getEnding(score);const next={...save,coins:save.coins+coins,bestScore:Math.max(save.bestScore,score),history:[...save.history,{score,coins,ending:ending.id,decisions,date:new Date().toISOString()}].slice(-20)};saveGame(next);setSave(next);setResult({score,coins,ending:ending.id,state,decisions});setScreen('result')}
 const choose=(choice:any)=>{const next=applyEffects(state,choice.effects);setState(next);setDecisions(d=>d+1); if(choice.nextEvent==='ending') finish(); else setEventId(choice.nextEvent||'end')}
 const buy=(id:string)=>{const item=shopItems.find(x=>x.id===id);if(!item||save.coins<item.priceCoins)return;const next={...save,coins:save.coins-item.priceCoins,inventory:{...save.inventory,[id]:(save.inventory[id]||0)+1}};saveGame(next);setSave(next)}
 return <main><header><button className="logo" onClick={()=>setScreen('home')}>CONSEQUENCES</button><div className="coins">🪙 {save.coins}</div></header>
 {screen==='home'&&<section className="hero"><span className="eyebrow">LA OFICINA</span><h1>Un día normal.<br/><em>Probablemente.</em></h1><p>Cada decisión cambia algo. Algunas cosas tardan un poco en romperse.</p><button className="primary" onClick={startRun}>▶ Nueva run</button><button className="secondary" onClick={()=>setScreen('shop')}>🛒 Shop</button>{save.bestScore>0&&<div className="best">Mejor score <strong>{save.bestScore}</strong></div>}</section>}
 {screen==='run'&&event&&<section className="game"><div className="stats">{[['💵','money'],['★','reputation'],['👔','bossTrust'],['🤝','coworkerTrust'],['⚡','stress'],['🔎','information']].map(([icon,key])=><div key={key}><span>{icon}</span><b>{state[key as keyof GameState]}</b><small>{key}</small></div>)}</div><div className="event"><span className="counter">DECISIÓN {decisions+1}</span><h2>{event.text}</h2><div className="choices">{event.choices.map(c=><button key={c.id} disabled={!meets(state,c.conditions)} onClick={()=>choose(c)}><span>{c.id.toUpperCase()}</span>{c.text}{!meets(state,c.conditions)&&<small>🔒 Requiere más información</small>}</button>)}</div></div></section>}
 {screen==='result'&&result&&<section className="result"><span className="eyebrow">RUN TERMINADA</span><h1>{result.ending==='promotion'?'ASCENSO ACCIDENTAL':result.ending==='survivor'?'EMPLEADO DEL MES':'DÍA COMPLICADO'}</h1><div className="score"><small>SCORE</small><strong>{result.score}</strong></div><div className="reward">+{result.coins} 🪙 Coins</div><p>{events.length} eventos disponibles · {result.decisions} decisiones tomadas</p><button className="primary" onClick={startRun}>↻ Jugar otra vez</button><button className="secondary" onClick={()=>setScreen('shop')}>🛒 Shop</button><div className="admock"><b>🎬 ¿Querés duplicar tus Coins?</b><span>Ver anuncio <small>(demo)</small></span><button onClick={()=>{const next={...save,coins:save.coins+result.coins};saveGame(next);setSave(next)}}>×2 recompensa</button></div></section>}
 {screen==='shop'&&<section className="shop"><span className="eyebrow">TIENDA</span><h1>Prepará tu próxima<br/><em>mala decisión.</em></h1><div className="items">{shopItems.map(item=><article key={item.id}><div><span className="pill">{item.type}</span><h3>{item.name}</h3><p>{item.description}</p></div><button disabled={save.coins<item.priceCoins} onClick={()=>buy(item.id)}>{item.priceCoins} 🪙</button>{save.inventory[item.id]>0&&<small>En inventario: {save.inventory[item.id]}</small>}</article>)}</div><button className="secondary" onClick={()=>setScreen('home')}>← Volver</button></section>}
 </main>
}
export default App
